Reallsite/urls.py
from django.contrib import admin
from django.urls import path,include
from store import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('master/',views.base,name='base'),
    path('',views.index,name='index'),


    path('signup/',views.Signup, name='signup'),

    path('login/',views.Login,name='login'),
    path('change/', views.change_pass, name='changepass'),
    path('logout/', views.Logout, name='logout'),
   # path('account/',include('django.contrib.auth.urls')),
    path('detail/',views.cart_detail,name='detail'),
    path('con/',views.contact,name='contact'),
    path('checkout/',views.Checkout,name='checkout'),
    path('order/',views.order,name='order'),
    path('product/',views.product,name='product'),
    path('order_detail/<int:id>',views.order_detail,name='order_detail'),
    path('search/',views.search,name='search'),
# shopping-cart links
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/',views.cart_detail,name='cart_detail'),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Cetagory(models.Model):
    name=models.CharField(max_length=70)

    def __str__(self):
        return self.name

class Sub_Cetagory(models.Model):
    name = models.CharField(max_length=70)
    cetagory = models.ForeignKey(Cetagory,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
class Brand(models.Model):
    name=models.CharField(max_length=70,)

    def __str__(self):
        return self.name

class contact_us(models.Model):
    name= models.CharField(max_length=70)
    email= models.CharField(max_length=70)
    subject=models.CharField(max_length=70)
    message=models.CharField(max_length=70)



class Product(models.Model):
    Availability = (('In the stock','In the stock'),('out the stock ','Out the Stock'))
    cetagory = models.ForeignKey( Cetagory,on_delete=models.CASCADE,null=False,default='')
    sub_cetagory = models.ForeignKey(Sub_Cetagory,on_delete=models.CASCADE,null=False,default='')
    Brand = models.ForeignKey(Brand,on_delete=models.CASCADE,null=True,default='')
    image = models.ImageField(upload_to='ecommerce/pimg')
    name = models.CharField(max_length=70)
    price = models.IntegerField()
    Availability =models.CharField(choices=Availability,null=True,max_length=70)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    image=models.ImageField(upload_to='ecommerce/pimg/')
    product=models.CharField(max_length=70)
    user = models.ForeignKey(User,on_delete=models.CASCADE,default='')
    quantity=models.CharField(max_length=70)
    price = models.FloatField(max_length=70)
    address= models.TextField(null=True,blank=True)
    phone = models.CharField(max_length=70,default='')
    pincode = models.CharField(max_length=70,null=True,blank=True)
    total = models.CharField(max_length=70,default='')
    date = models.DateTimeField(default=datetime.datetime.today)

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    password1 = forms.CharField(label ='Confirm Password',widget = forms.PasswordInput(attrs = {'class':'form-control','placeholder':'Enter your password'}))
    password2 = forms.CharField(label = 'Confirm Password Again',widget= forms.PasswordInput(attrs = {'class':'form-control','placeholder':'Enter your password Again'}))
    class Meta:
        model = User
        fields = ['username','email']
        label = {'email':'Email'}
        widgets = {'username': forms.TextInput(attrs={'class': 'form-control','placeholder':'Enter your username without space'}),
                   'email': forms.EmailInput(attrs={'class': 'form-control','placeholder':'Enter your Email '})}


class loginForm(AuthenticationForm):

    username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(label=('password'), widget=forms.PasswordInput(attrs={'autofocus': True, 'autocomplete': 'current-password', 'class': 'form-control'}))
#
# class Postform(forms.ModelForm):
#     class Meta:
#         model = Post
#
#         fields=['titel','des']
#         labels = {'titel':'Titel','des':'Descrtiption'}
#         widgets = {'titel':forms.TextInput(attrs={'class':'form-control'}),
#         'des':forms.Textarea(attrs={'class':'form-control'})}

store/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,HttpResponse
from .models import Cetagory,Product,contact_us,Order,Brand
from .forms import SignupForm,loginForm
from django.contrib import messages
from django.contrib.auth import authenticate ,login,logout
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from cart.cart import Cart
from django.contrib.auth.models import User
# Create your views here.

def base(request):
    return render(request,'base.html')


def index(request):
    cetagory = Cetagory.objects.all()
    brand =Brand.objects.all()
    brandID = request.GET.get('brand')
    cetagoryID = request.GET.get('cetagory')
    if cetagoryID:
        product=Product.objects.filter(sub_cetagory=cetagoryID).order_by('-id')
    elif brandID:
        product = Product.objects.filter(Brand=brandID).order_by('-id')
    else:
        product =Product.objects.all()
    return render(request,'index.html',{'pro':cetagory,'duct':product,'brand':brand,'product':product})

def Signup(request):
        if request.method == 'POST':
            fm = SignupForm(request.POST)
            if fm.is_valid():
                fm.save()
                messages.success(request,'Your account has been created')
        else:
            fm = SignupForm()
        return render(request, 'Registerform.html', {'form': fm})

def Login(request):
    if request.method =="POST":
        fm =loginForm(request=request , data= request.POST)
        if fm.is_valid():
            messages.success(request,'You have been login..')
            uname = fm.cleaned_data['username']
            upas = fm.cleaned_data['password']
            user = authenticate(username=uname , password=upas)
            if user is not None:
               login(request,user)
               return HttpResponseRedirect('/')
    else:
        fm = loginForm
    return render(request,'login.html',{'form':fm})

def  Logout(request):
    logout(request)
    return HttpResponseRedirect('/')

def change_pass(request):
    if request.method =='POST':
        fm=PasswordChangeForm(user=request.user,data=request.POST)
        if fm.is_valid():
            fm.save()
            return HttpResponseRedirect('/login/')
    else:
        fm=PasswordChangeForm(user=request.user)
    return render(request,'changepass.html',{'form':fm})

@login_required(login_url="/login/")
def cart_add(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("index")


@login_required(login_url="/login/")
def item_clear(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("cart_detail")


@login_required(login_url="/login/")
def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("cart_detail")


@login_required(login_url="/login/")
def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("cart_detail")


@login_required(login_url="/login/")
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("cart_detail")


@login_required(login_url="/login/")
def cart_detail(request):
    return render(request, 'cart_detail.html')

def contact(request):
    if request.method =='POST':
        user=contact_us(name=request.POST.get('name'),
                        email=request.POST.get('email'),
                        subject=request.POST.get('subject'),
                        message=request.POST.get('message'))
        user.save()
    return render(request,'Contact.html')

def Checkout(request):
    if request.method =='POST':
        # phone = request.POST.get('phone')
        address=request.POST.get('address')
        phone = request.POST.get("phone")
        pincode = request.POST.get('pincode')
        cart = request.session.get('cart')
        uid = request.session.get('_auth_user_id')
        user = User.objects.get(pk = uid)
        # print(phone,pincode,message,cart,user)

        for i in cart:
            a = int(cart[i]['price'])
            b = cart[i]['quantity']
            total = a + b
            order = Order(
                user = user,
                product = cart[i]['name'],
                price = cart[i]['price'],
                quantity = cart[i]['quantity'],
                image = cart[i]['image'],
                address = address,
                phone = phone,
                pincode = pincode,
                total = total
            )
            order.save()
        request.session['cart']={}
        return redirect('index')



    return HttpResponse('This is Checkout page ')


def order(request):
    uid = request.session.get('_auth_user_id')
    user = User.objects.get(pk=uid)
    Order = order.objects.filter(user = user )
    print(user,Order)
    return render(request,'order.html',{'order':Order})

def product(request):
    cetagory = Cetagory.objects.all()
    brand = Brand.objects.all()
    brandID = request.GET.get('brand')
    cetagoryID = request.GET.get('cetagory')
    if cetagoryID:
        product = Product.objects.filter(sub_cetagory=cetagoryID).order_by('-id')
    elif brandID:
        product = Product.objects.filter(Brand=brandID).order_by('-id')
    else:
        product = Product.objects.all()

    return render(request,'product.html',{'pro':cetagory,'brand':brand,'duct':product})

def order_detail(reqeust,id):
    product=Product.objects.filter(id=id).first()
    return render(reqeust,'product_detail.html',{'product':product})
def search(request):
    query = request.GET.get('query','')

    product = Product.objects.filter(name__icontains=query)
    return render(request,'search.html',{'product':product})

store/templates/Checkout.html
{% extends 'base.html'%}
{% block body %}
{% endblock %}

store/templates/Contact.html
{% extends 'base.html'%}
{% block body %}
<div id="contact-page" class="container">
    	<div class="bg">
	    	<div class="row">
	    		<div class="col-sm-12">
					<h2 class="title text-center">Contact <strong>Us</strong></h2>
					<div id="gmap" class="contact-map" style="width:100%">
                      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d27229.747948148477!2d74.29070830935903!3d31.449415970644583!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3919014ca50af181%3A0x6630f48affe03d5d!2sTownship%20Lahore%2C%20Punjab%2C%20Pakistan!5e0!3m2!1sen!2s!4v1637241061149!5m2!1sen!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
					</div>
				</div>
			</div>
    		<div class="row">
	    		<div class="col-sm-8">
	    			<div class="contact-form">
	    				<h2 class="title text-center">Get In Touch</h2>
	    				<div class="status alert alert-success" style="display: none"></div>
				    	<form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
				            {% csrf_token %}
							<div class="form-group col-md-6">
				                <input type="text" name="name" class="form-control" required="required" placeholder="Name">
				            </div>
				            <div class="form-group col-md-6">
				                <input type="email" name="email" class="form-control" required="required" placeholder="Email">
				            </div>
				            <div class="form-group col-md-12">
				                <input type="text" name="subject" class="form-control" required="required" placeholder="Subject">
				            </div>
				            <div class="form-group col-md-12">
				                <textarea name="message" id="message" required="required" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
				            </div>
				            <div class="form-group col-md-12">
				                <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
				            </div>
				        </form>
	    			</div>
	    		</div>
	    		<div class="col-sm-4">
	    			<div class="contact-info">
	    				<h2 class="title text-center">Contact Info</h2>
	    				<address>
	    					<p>E-Shopper</p>
							<p>Township lahore</p>
							<p>Lahore Pakistan</p>
							<p>Mobile: +92 3045890718</p>
							<p>Fax: 1-714-252-0026</p>
							<p>Email: info@e-shopper.com</p>
	    				</address>
	    				<div class="social-networks">
	    					<h2 class="title text-center">Social Networking</h2>
							<ul>
								<li>
									<a href="#"><i class="fa fa-facebook"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-twitter"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-google-plus"></i></a>
								</li>
								<li>
									<a href="#"><i class="fa fa-youtube"></i></a>
								</li>
							</ul>
	    				</div>
	    			</div>
    			</div>
	    	</div>
    	</div>
    </div><!--/#contact-page-->

{% endblock %}

store/templates/Registerform.html
{%extends 'base.html'%}
{% block body %}
<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h1>Registeration Form</h1>
						<form action="" method="POST" style="labe">
                             {% csrf_token %}
                             {% for fm in form %}
                             {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}<br><br>
                                {% endfor %}
							<input type="submit" class="btn btn-primary text-white" value="Submit">
							<span style="margin-left:150px; mb-2">Already have an Account</span>&nbsp<a href="{% url 'login'%}">Login</a>
                        </form>
					</div><!--/login form-->
				</div>
			</div>
		</div>
{% endblock %}

store/templates/cart_detail.html
{% extends 'base.html'%}
{% load cart_tag %}
{% block body %}
<section id="cart_items">
		<div class="container">
			<div class="breadcrumbs">
				<ol class="breadcrumb">
				  <li><a href="{% url 'index'%}">Home</a></li>
				  <li class="active">Shopping Cart</li>
				</ol>
			</div>
			<div class="table-responsive cart_info">
				<table class="table table-condensed">
					<thead>
						<tr class="cart_menu">
							<td class="image">Item</td>
							<td class="description"></td>
							<td class="price">Price</td>
							<td class="quantity">Quantity</td>
							<td class="total">Total</td>
							<td></td>
						</tr>
					</thead>
					<tbody>
					<a href="{% url 'cart_clear' %}">Clear Cart</a>
					{% for key,value in request.session.cart.items %}
						<tr>
							<td class="cart_product">
								<a href=""><img src="{{value.image}}" alt="" style="height:150px;"></a>
							</td>
							<td class="cart_description">
								<h4><a href="">{{value.name}}</a></h4>
								<p>${{value.price}}</p>
							</td>
							<td class="cart_quantity">
								<div class="cart_quantity_button">
									<a class="cart_quantity_up" href="{% url 'item_increment' value.product_id %}"> + </a>
									<input class="cart_quantity_input" type="text" name="quantity" value="{{value.quantity}}" autocomplete="off" size="2">
									<a class="cart_quantity_down" href="{% url 'item_decrement' value.product_id %}"> - </a>
								</div>
							</td>
							<td class="cart_total">
								<p class="cart_total_price"> ${{value.price|multiply:value.quantity }}</p>
							</td>
							<td class="cart_delete">
								<a class="cart_quantity_delete" href="{% url 'item_clear' key %}"><i class="fa fa-times"></i></a>
							</td>
						</tr>

						<tr>
					{% endfor %}
					</tbody>
					<tfoot>
					<td>

					</td>
					<td>

					</td>
					<td>
						<h2>Sub Total:</h2>
					</td>

					<td>
					<h3>{{cart_total_amount}}</h3>
					</td>

					</tfoot>

				</table>
				<button type="submit" class="btn btn-primary " style="float:right;" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Checkout</button>
			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			  <div class="modal-dialog" role="document">
				<div class="modal-content">
				  <div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">New message</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
				  </div>
				  <div class="modal-body">
					<form  method="POST" action="/checkout/">
						{% csrf_token %}
						<div class="form-group">
						<label for="message-text" class="col-form-label">Phone:</label>
						<textarea class="form-control" name="phone" id="message-text"></textarea>
					  </div>
					  <div class="form-group">
						<label for="recipient-name" class="col-form-label">Message:</label>
						  <input type="text" class="form-control"  name="message" id="recipient-name"></textarea>
					  </div>
					  <div class="form-group">
						<label for="message-text" class="col-form-label">Pincode:</label>
						<textarea class="form-control"  name=" pincode" id="message-text"></textarea>
					  </div>
						<div class="modal-footer">
					<button type="submit" class="btn btn-primary">Send message</button>
				  </div>
					</form>
				  </div>
				</div>
			  </div>
			</div>
			</div>
		</div>
	</section> <!--/#cart_items-->

{% endblock %}

store/templates/changepass.html
{%extends 'base.html'%}
{% block body %}
<section id="form"><!--form-->
		<div class="container">
			<div class="row">
				<div class="col-sm-4 col-sm-offset-1">
					<div class="login-form"><!--login form-->
						<h1>Change Password</h1>
						<form action="" method="POST" style="">
                             {% csrf_token %}
                             {% for fm in form %}
                             {{fm.label_tag}} {{fm}} {{fm.errors|striptags}}<br><br>
                                {% endfor %}
                            <input type="submit" class="btn btn-primary text-white" value="Save">
                        </form>
					</div><!--/login form-->
				</div>
			</div>
		</div>
{% endblock %}

store/templates/index.html
{% extends 'base.html'%}
{% block body %}
{% load static %}
<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class=""></li>
							<li data-target="#slider-carousel" data-slide-to="1" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="2" class=""></li>
						</ol>

						<div class="carousel-inner">
							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free E-Commerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/girl1.jpg'%}" class="girl img-responsive" alt="">
									<img src="{% static 'images/home/pricing.png'%}" class="pricing" alt="">
								</div>
							</div>
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>100% Responsive Design</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/girl2.jpg'%}" class="girl img-responsive" alt="">
									<img src="{% static 'images/home/pricing.png'%}" class="pricing" alt="">
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>E</span>-SHOPPER</h1>
									<h2>Free Ecommerce Template</h2>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
									<button type="button" class="btn btn-default get">Get it now</button>
								</div>
								<div class="col-sm-6">
									<img src="{% static 'images/home/girl3.jpg'%}" class="girl img-responsive" alt="">
									<img src="{% static 'images/home/pricing.png'%}" class="pricing" alt="">
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section>
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for cart in pro %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cart.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cart.name}}
										</a>
									</h4>
								</div>
								<div id="{{cart.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cart.sub_cetagory_set.all%}
											<li><a href="/?cetagory={{i.id}}&brand{{brand.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}
						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								{% for i in brand %}
								<ul class="nav nav-pills nav-stacked">
									<li><a href="/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{ i.name }}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well text-center">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						{% for product in duct %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="{{product.image}}" alt="" />
											<h2>${{product.price}}</h2>
											<p>{{product.name}}</p>
											<a href="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>${{product.price}}</h2>
												<p>Easy Polo Black Edition</p>
												<a href ="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
										<li><a href="#"><i class="fa fa-plus-square"></i>Add to compare</a></li>
									</ul>
								</div>
							</div>
						</div>
						{% endfor %}
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>
{% endblock %}

store/templates/product.html
{% extends 'base.html'%}
{% block body %}
<section>
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="left-sidebar">
						<h2>Category</h2>
						<div class="panel-group category-products" id="accordian"><!--category-productsr-->
							{% for cart in pro %}
							<div class="panel panel-default">
								<div class="panel-heading">
									<h4 class="panel-title">
										<a data-toggle="collapse" data-parent="#accordian" href="#{{cart.id}}">
											<span class="badge pull-right"><i class="fa fa-plus"></i></span>
											{{cart.name}}
										</a>
									</h4>
								</div>
								<div id="{{cart.id}}" class="panel-collapse collapse">
									<div class="panel-body">
										<ul>
											{% for i in cart.sub_cetagory_set.all%}
											<li><a href="/product/?cetagory={{i.id}}&brand{{brand.id}}">{{i.name}} </a></li>
											{% endfor %}
										</ul>
									</div>
								</div>
							</div>
							{% endfor %}
						</div><!--/category-products-->

						<div class="brands_products"><!--brands_products-->
							<h2>Brands</h2>
							<div class="brands-name">
								{% for i in brand %}
								<ul class="nav nav-pills nav-stacked">
									<li><a href="/product/?brand={{i.id}}"> <span class="pull-right">(50)</span>{{ i.name }}</a></li>
									{% endfor %}
								</ul>
							</div>
						</div><!--/brands_products-->

						<div class="price-range"><!--price-range-->
							<h2>Price Range</h2>
							<div class="well">
								 <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
								 <b>$ 0</b> <b class="pull-right">$ 600</b>
							</div>
						</div><!--/price-range-->

						<div class="shipping text-center"><!--shipping-->
							<img src="images/home/shipping.jpg" alt="" />
						</div><!--/shipping-->

					</div>
				</div>

				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">Features Items</h2>
						{% for product in duct %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
										<div class="productinfo text-center">
											<img src="/{{product.image}}" alt="" />
											<h2>${{product.price}}</h2>
											<p>{{product.name}}</p>
											<a href="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
										</div>
										<div class="product-overlay">
											<div class="overlay-content">
												<h2>${{product.price}}</h2>
												<p>{{product.name}}</p>
												<a href ="{% url 'cart_add' product.id %}" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</div>
										</div>
								</div>
								<div class="choose">
									<ul class="nav nav-pills nav-justified">
										<li><a href="{% url 'order_detail' product.id %}"><i class="fa fa-plus-square"></i>View Detail</a></li>
									</ul>
								</div>
							</div>
						</div>
						{% endfor %}
					</div>
						<ul class="pagination">
							<li class="active"><a href="">1</a></li>
							<li><a href="">2</a></li>
							<li><a href="">3</a></li>
							<li><a href="">&raquo;</a></li>
						</ul>
					</div><!--features_items-->
				</div>
			</div>
		</div>
	</section>
{% endblock %}